### ISSUE TITLE
Modules not stopping

### ISSUE THREAD

**Issue by kraj011** [Team6090/SwerveIO#22]
**Describe the bug**
Finally got around to implementing this into our code, but unfortunately I'm running into some issues. When I throttle and let go of the controller joystick, the modules keep running and don't stop.

**To Reproduce**

1. Implement SwerveIO with default SwerveDriveTeleop command
2. Drive

**Expected behavior**

The module should respond to a 0 joystick position and slow down / stop.

**Comment by jordanbancino** [comment]
Oh, very interesting. This could be the velocity loop on the Spark Max.... or a few other things. We've never had this problem before. Do the modules respond to the joystick at all?

One suggestion I have right off the bat is to check out our `log` package. You can set up a `DashboardSwerveLogger` that will output the state of the swerve drive to the SmartDashboard. Here you can see live all the inputs and outputs of the SwerveIO. To get started with that, just call

```java
startLogging(new DashboardSwerveLogger());
```

on your swerve drive object. Additionally, there's `log.csv`. This package will allow you to generate CSV files that log everything the swerve drive is taking in and outputting. You can take a look at `CSVSwerveLogger`, which outputs all the following information:

[CSVSwerveLogger.java:33](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/log/csv/CSVSwerveLogger.java#L33):
```java
super(csv,
                "time,joystickX,joystickY,joystickZ,gyroYaw,"
                        + "frontLeftPivotEncoder,frontLeftPivotSpeed,frontLeftDriveEncoder,frontLeftDriveSpeed,"
                        + "frontRightPivotEncoder,frontRightPivotSpeed,frontRightDriveEncoder,frontRightDriveSpeed,"
                        + "rearLeftPivotEncoder,rearLeftPivotSpeed,rearLeftDriveEncoder,rearLeftDriveSpeed,"
                        + "rearRightPivotEncoder,rearRightPivotSpeed,rearRightDriveEncoder,rearRightDriveSpeed");
```

You can also look at `CSVPIDSwerveLogger`, which logs the inputs and outputs of a single module. For the module you specify, it will output these fields:

[CSVPIDSwerveLogger.java:35](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/log/csv/CSVPIDSwerveLogger.java#L35):
```java
super(csv, "time,fwd,str,rcw,setpoint,feedback,feedbackMod,difference,output");
```

You can see exactly how to set these up in our [SwerveIOTestBase project's Drivetrain.java](https://github.com/Team6090/SwerveIOTestBase/blob/master/src/main/java/frc/robot/subsystems/DriveTrain.java#L119). I'd recommend you start with the `DashboardSwerveLogger` to see exactly what is happening live, but if that doesn't work, then feel free to upload CSV files here and we can take a look. I am also ready to build up the logging API as needed, I know it's pretty barebones right now, so if there's something we can do to improve the log output, let us know, or feel free to open a pull request!

Oh, by the way, our [`shuffleboard.json`](https://github.com/Team6090/SwerveIOTestBase/blob/master/shuffleboard.json) will probably be quite helpful to you with the `DashboardSwerveLogger`. We use Shuffleboard because of how easy it is to organize network tables data. We have that configuration set up just for SwerveIO.

Additionally, since SwerveIO is in such early stages of development and is changing quickly, I'd recommend just adding it as a git submodule to your project, or a Gradle source dependency. I'm not sure how you guys are currently pulling it, but there's a likely possibility you've got an older version if you're using our team's vendor dependency JSON like the README says.

By the way, thank you for being so patient with us and taking the time to look at what we're doing here, it's greatly appreciated 😃

**Comment by kraj011** [comment]
Of course! So yea it responds initially to joystick input but once i let go it doesn’t stop. I will definetely try out the logging stuff later today! For testing purposes i just cloned the repo and put it into our project, so i should be on the latest version. Ill put it in as a git submodule later today and will definetely keep you posted!!

**Comment by jordanbancino** [comment]
Huh, very interesting indeed. Alright, cool! Ah okay, cool, yeah that's a good idea, to just clone it in. Awesome, thanks!

**Comment by kraj011** [comment]
Ok i see whats going on. It is slowing down, just insanely slow. If i go full speed and let go, it takes around 20 seconds to come back to stop. Am i doing something wrong implementing? I am logging the input values and everything seems correct so thats a good sign!

**Comment by kraj011** [comment]
And whats interesting is when i disable it lets say halfway through stopping, once i re enable it doesnt stop it actually goes back to the speed at which i stopped it and keeps slowing down from there. I dont think the wheels are coasting because if i apply some pressure manually they dont stop, so the code is passing in smaller and smaller motor values.

**Comment by jordanbancino** [comment]
Oh that's very interesting. My immediate thought is to check that your motor controllers are set to brake mode. Are the drive Spark Maxes set to brake mode? I believe the LEDs will flash cyan when idling if they are. But then yeah... if you try to drag the wheels, they should stop. Do you have a ramp rate set anywhere? Either on the Spark Max, or somewhere else in the code?

**Comment by kraj011** [comment]
I don't believe they are set in brake mode that might be it. I'll switch them in a few minutes and post back here!

**Comment by jordanbancino** [comment]
Alright. I do know that that caused us a similar problem so hopefully that'll fix it!

**Comment by kraj011** [comment]
Welp nevermind. Turns out our drive motors were already in brake mode. Anything else you suggest I should try?

**Comment by jordanbancino** [comment]
Oh, darn. Hmmmm. You could try running raw current to the motors and seeing if that works... unfortunately there's no easy way to do that. Well, okay, it isn't difficult if you're compiling from source. Try commenting out this entire function:

```java
@Override
public void setDriveMotorSpeed(double ref) {
    driveMotor.getPIDController().setReference(ref * getDriveMaxRPM(), ControlType.kVelocity);
}
```

in [MK2SwerveModule.java](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/module/MK2SwerveModule.java#L106). What that will do is revert back to the superclass function, which will run a raw current reference into the motors (via [this function](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/module/GenericSwerveModule.java#L109)), which will completely bypass the velocity loop on the Spark Max PID controller. That way we can start narrowing it down. If it's the velocity loop, then we can mess with tuning. If not, then we can keep looking.

**Comment by kraj011** [comment]
Yea that seems to be it. I commented it out and it worked so I guess it is the velocity loop thats causing problems.

**Comment by jordanbancino** [comment]
Very interesting. The Spark Max PID controllers have always been finicky like that. I've never liked using them. So is everything working now? Are you guys okay with just running raw current references? The only reason we are using the velocity loop is to ensure that all modules stay consistent at the speed we're giving them, but honestly, we don't really notice any difference.

**Comment by kraj011** [comment]
Yea honestly I mean right now im running tests with our drivetrain on top of some blocks but what I'll do is run actual tests with it driving and let you know. Another question I have: I have our "zero" module references from when we used SDS's code, however they seem to be different when I run SwerveIO. How do you suggest I pull the zero module encoder values using SwerveIO? Once I get that I'll be able to run more extensive tests to hopefully further the development of this lib!

**Comment by kraj011** [comment]
Forgot i turned on swerve logging lol... should the encoder values be this high? Im getting some values above 1000 for the “encoder” values. Am i looking at the wrong values?

**Comment by kraj011** [comment]
Ignore me i just can’t read... those are drive encoder values 😂

**Comment by jordanbancino** [comment]
Ah alright, good idea. That sounds good. Now that's a very good question. I have no idea how SDS does their encoders (I'm guessing by voltage 0 to 5 volts), but the `AnalogEncoder` class returns the encoder reading scaled from 0 to 360 degrees. Therefore, when you get the readings, they'll be in degrees. What we do to calibrate our encoders is set all of our software offsets to 0, then we use a length of metal to set all four modules straight (to their "zero") orientation. Then we read the encoder values from the Shuffleboard and set these as our offsets in the code.

---

Hahaha, yep, make sure you look at the pivot encoder readings  😂

**Comment by kraj011** [comment]
That did the trick! Closing this thread off!

**Comment by jordanbancino** [comment]
Awesome!
