### ISSUE TITLE
Possible addition?

### ISSUE THREAD

**Issue by kraj011** [Team6090/SwerveIO#8]
Do you think it would be helpful in the initialize method of the example command that the user calls the reset or zero methods of the SwerveDrive subsystem before the command runs to reset the encoders in case they have some sort of encoder logic? Just a quick thought I had.

**Comment by jordanbancino** [comment]
Yes, possibly. It all depends on the encoders though. The MK2 modules use absolute encoders, so they'll hold their position across power cycles. We use this to know where zero is and have the wheels automatically snap to the starting spot. So in our case, we don't want to reset them because we need to know where the encoder is positioned on initialization. But for relative encoders, yes, absolutely, you'd want to make sure they're zeroed.

**Comment by kraj011** [comment]
Gotcha that makes perfect sense! Thanks for the clarification!

**Comment by jordanbancino** [comment]
No problem!
